CREATE TABLE IF NOT EXISTS ${table_name} (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_id    VARCHAR(128)  NOT NULL,
    partition_key   VARCHAR(128)  NOT NULL,
    event_type      VARCHAR(128)  NOT NULL,
    payload         JSONB         NOT NULL,
    headers         JSONB,
    status          INT           NOT NULL,
    retry_count     INT           NOT NULL DEFAULT 0,
    locked_by       VARCHAR(128),
    locked_until    TIMESTAMPTZ,
    trace_parent    TEXT,
    sent_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    PRIMARY KEY (status, id)
) PARTITION BY RANGE (status);

CREATE TABLE IF NOT EXISTS ${table_name}_active
    PARTITION OF ${table_name}
    FOR VALUES FROM (MINVALUE) TO (100);

CREATE TABLE IF NOT EXISTS ${table_name}_archive
    PARTITION OF ${table_name}
    FOR VALUES FROM (100) TO (MAXVALUE);

CREATE INDEX IF NOT EXISTS idx_${table_name}_status_locked_until
    ON ${table_name} (status, locked_until);
